stages:
  - format
  - clippy
  - build
  - publish

rust-format:
  stage: format
  image: rustlang/rust:nightly
  script:
    - cargo fmt -- --check
  allow_failure: true

rust-clippy:
  stage: clippy
  image: rustlang/rust:nightly
  script:
    - cargo clippy --all-features 
  allow_failure: true

rust-all-features:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose --all-features
    - cargo test --verbose --all-features

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly-serde:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --features serialize --verbose
    - cargo test --features serialize --verbose

rust-stable:
  stage: build
  image: rust
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

rust-stable-serde:
  stage: build
  image: rust
  script:
    - cargo build --features serialize --verbose
    - cargo test --features serialize --verbose
  allow_failure: true

publish:
  stage: publish
  image: rustlang/rust:nightly
  script:
    - cargo login $CRATES_IO_TOKEN
    - cargo package
    - cargo publish
  allow_failure: true

