stages:
  - format
  - clippy
  - build
  - publish

rust-format:
  stage: format
  image: rust
  script:
    - cargo fmt -- --check

rust-clippy:
  stage: clippy
  image: rust
  script:
    - cargo clippy --all-features

rust-stable:
  stage: build
  image: rust
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-stable-serde:
  stage: build
  image: rust
  script:
    - cargo build --features serialize --verbose
    - cargo test --features serialize --verbose

publish:
  stage: publish
  image: rust
  script:
    - cargo login $CRATES_IO_TOKEN
    - cargo package
    - cargo publish

