stages:
  - build
  - publish

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly-serde:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --features serialize --verbose
    - cargo test --features serialize --verbose

rust-stable:
  stage: build
  image: rustlang/rust:stable
  script:
    - cargo build --verbose
    - cargo test --verbose


rust-stable-serde:
  stage: build
  image: rustlang/rust:stable
  script:
    - cargo build --features serialize --verbose
    - cargo test --features serialize --verbose


publish:
  stage: publish
  image: rustlang/rust:nightly
  script:
    - cargo login $CRATES_IO_TOKEN
    - cargo package
    - cargo publish

